//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeydbSpec) DeepCopyInto(out *KeydbSpec) {
	*out = *in
	if in.KeydbTolerations != nil {
		in, out := &in.KeydbTolerations, &out.KeydbTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeydbNetpolIngressExtraPorts != nil {
		in, out := &in.KeydbNetpolIngressExtraPorts, &out.KeydbNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.KeydbNetpolEgressExtraPorts != nil {
		in, out := &in.KeydbNetpolEgressExtraPorts, &out.KeydbNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeydbSpec.
func (in *KeydbSpec) DeepCopy() *KeydbSpec {
	if in == nil {
		return nil
	}
	out := new(KeydbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodle) DeepCopyInto(out *LMSMoodle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodle.
func (in *LMSMoodle) DeepCopy() *LMSMoodle {
	if in == nil {
		return nil
	}
	out := new(LMSMoodle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LMSMoodle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleList) DeepCopyInto(out *LMSMoodleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LMSMoodle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleList.
func (in *LMSMoodleList) DeepCopy() *LMSMoodleList {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LMSMoodleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleSpec) DeepCopyInto(out *LMSMoodleSpec) {
	*out = *in
	in.LMSMoodleTemplateSpec.DeepCopyInto(&out.LMSMoodleTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleSpec.
func (in *LMSMoodleSpec) DeepCopy() *LMSMoodleSpec {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleStatus) DeepCopyInto(out *LMSMoodleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleStatus.
func (in *LMSMoodleStatus) DeepCopy() *LMSMoodleStatus {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleTemplate) DeepCopyInto(out *LMSMoodleTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleTemplate.
func (in *LMSMoodleTemplate) DeepCopy() *LMSMoodleTemplate {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LMSMoodleTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleTemplateList) DeepCopyInto(out *LMSMoodleTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LMSMoodleTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleTemplateList.
func (in *LMSMoodleTemplateList) DeepCopy() *LMSMoodleTemplateList {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LMSMoodleTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleTemplateSpec) DeepCopyInto(out *LMSMoodleTemplateSpec) {
	*out = *in
	in.MoodleSpec.DeepCopyInto(&out.MoodleSpec)
	in.PostgresSpec.DeepCopyInto(&out.PostgresSpec)
	in.NfsSpec.DeepCopyInto(&out.NfsSpec)
	in.KeydbSpec.DeepCopyInto(&out.KeydbSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleTemplateSpec.
func (in *LMSMoodleTemplateSpec) DeepCopy() *LMSMoodleTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LMSMoodleTemplateStatus) DeepCopyInto(out *LMSMoodleTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LMSMoodleTemplateStatus.
func (in *LMSMoodleTemplateStatus) DeepCopy() *LMSMoodleTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(LMSMoodleTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoodleConfigProperty) DeepCopyInto(out *MoodleConfigProperty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoodleConfigProperty.
func (in *MoodleConfigProperty) DeepCopy() *MoodleConfigProperty {
	if in == nil {
		return nil
	}
	out := new(MoodleConfigProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MoodleSpec) DeepCopyInto(out *MoodleSpec) {
	*out = *in
	if in.MoodleCronjobTolerations != nil {
		in, out := &in.MoodleCronjobTolerations, &out.MoodleCronjobTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MoodleUpdateJobTolerations != nil {
		in, out := &in.MoodleUpdateJobTolerations, &out.MoodleUpdateJobTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MoodleNewInstanceJobTolerations != nil {
		in, out := &in.MoodleNewInstanceJobTolerations, &out.MoodleNewInstanceJobTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.MoodleConfigAdditionalCfg = in.MoodleConfigAdditionalCfg
	if in.MoodleNetpolIngressExtraPorts != nil {
		in, out := &in.MoodleNetpolIngressExtraPorts, &out.MoodleNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.MoodleNetpolEgressExtraPorts != nil {
		in, out := &in.MoodleNetpolEgressExtraPorts, &out.MoodleNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.NginxTolerations != nil {
		in, out := &in.NginxTolerations, &out.NginxTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NginxNetpolIngressExtraPorts != nil {
		in, out := &in.NginxNetpolIngressExtraPorts, &out.NginxNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.NginxNetpolEgressExtraPorts != nil {
		in, out := &in.NginxNetpolEgressExtraPorts, &out.NginxNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PhpFpmTolerations != nil {
		in, out := &in.PhpFpmTolerations, &out.PhpFpmTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PhpFpmNetpolIngressExtraPorts != nil {
		in, out := &in.PhpFpmNetpolIngressExtraPorts, &out.PhpFpmNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PhpFpmNetpolEgressExtraPorts != nil {
		in, out := &in.PhpFpmNetpolEgressExtraPorts, &out.PhpFpmNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	in.RoutineStatusCrNotify.DeepCopyInto(&out.RoutineStatusCrNotify)
	in.RoutineStatusCrNotifyTermination.DeepCopyInto(&out.RoutineStatusCrNotifyTermination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MoodleSpec.
func (in *MoodleSpec) DeepCopy() *MoodleSpec {
	if in == nil {
		return nil
	}
	out := new(MoodleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyExtraPort) DeepCopyInto(out *NetworkPolicyExtraPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyExtraPort.
func (in *NetworkPolicyExtraPort) DeepCopy() *NetworkPolicyExtraPort {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyExtraPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NfsSpec) DeepCopyInto(out *NfsSpec) {
	*out = *in
	if in.GaneshaTolerations != nil {
		in, out := &in.GaneshaTolerations, &out.GaneshaTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GaneshaNetpolIngressExtraPorts != nil {
		in, out := &in.GaneshaNetpolIngressExtraPorts, &out.GaneshaNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.GaneshaNetpolEgressExtraPorts != nil {
		in, out := &in.GaneshaNetpolEgressExtraPorts, &out.GaneshaNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NfsSpec.
func (in *NfsSpec) DeepCopy() *NfsSpec {
	if in == nil {
		return nil
	}
	out := new(NfsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.PostgresTolerations != nil {
		in, out := &in.PostgresTolerations, &out.PostgresTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostgresNetpolIngressExtraPorts != nil {
		in, out := &in.PostgresNetpolIngressExtraPorts, &out.PostgresNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PostgresNetpolEgressExtraPorts != nil {
		in, out := &in.PostgresNetpolEgressExtraPorts, &out.PostgresNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PostgresReadreplicasTolerations != nil {
		in, out := &in.PostgresReadreplicasTolerations, &out.PostgresReadreplicasTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PgbouncerTolerations != nil {
		in, out := &in.PgbouncerTolerations, &out.PgbouncerTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PgbouncerNetpolIngressExtraPorts != nil {
		in, out := &in.PgbouncerNetpolIngressExtraPorts, &out.PgbouncerNetpolIngressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PgbouncerNetpolEgressExtraPorts != nil {
		in, out := &in.PgbouncerNetpolEgressExtraPorts, &out.PgbouncerNetpolEgressExtraPorts
		*out = make([]NetworkPolicyExtraPort, len(*in))
		copy(*out, *in)
	}
	if in.PgbouncerReadonlyTolerations != nil {
		in, out := &in.PgbouncerReadonlyTolerations, &out.PgbouncerReadonlyTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutineStatusCrNotify) DeepCopyInto(out *RoutineStatusCrNotify) {
	*out = *in
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = make([]int8, len(*in))
		copy(*out, *in)
	}
	out.Headers = in.Headers
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutineStatusCrNotify.
func (in *RoutineStatusCrNotify) DeepCopy() *RoutineStatusCrNotify {
	if in == nil {
		return nil
	}
	out := new(RoutineStatusCrNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutineStatusCrNotifyHeaders) DeepCopyInto(out *RoutineStatusCrNotifyHeaders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutineStatusCrNotifyHeaders.
func (in *RoutineStatusCrNotifyHeaders) DeepCopy() *RoutineStatusCrNotifyHeaders {
	if in == nil {
		return nil
	}
	out := new(RoutineStatusCrNotifyHeaders)
	in.DeepCopyInto(out)
	return out
}
