PROJECT_SHORTNAME ?= lms-moodle
VERSION ?= 0.6.10
MOODLE_OPERATOR_VERSION ?= 0.6.38
POSTGRES_OPERATOR_VERSION ?= 0.3.29
KEYDB_OPERATOR_VERSION ?= 0.3.31
NFS_OPERATOR_VERSION ?= 0.4.30
OPERATOR_TYPE ?= go
PROJECT_TYPE ?= $(OPERATOR_TYPE)-operator
COMMUNITY_OPERATOR_NAME ?= lms-moodle-operator

include hack/mk/main.mk
