PROJECT_SHORTNAME ?= lms-moodle
VERSION ?= 0.4.6
MOODLE_OPERATOR_VERSION ?= 0.6.18
POSTGRES_OPERATOR_VERSION ?= 0.3.13
KEYDB_OPERATOR_VERSION ?= 0.3.14
NFS_OPERATOR_VERSION ?= 0.4.13
OPERATOR_TYPE ?= go
PROJECT_TYPE ?= $(OPERATOR_TYPE)-operator
COMMUNITY_OPERATOR_NAME ?= lms-moodle-operator

include hack/mk/main.mk
