PROJECT_SHORTNAME ?= kio
VERSION ?= 0.3.46
MOODLE_OPERATOR_VERSION ?= 0.6.6
POSTGRES_OPERATOR_VERSION ?= 0.3.3
NFS_OPERATOR_VERSION ?= 0.4.3
KEYDB_OPERATOR_VERSION ?= 0.3.4
OPERATOR_TYPE ?= go
PROJECT_TYPE ?= $(OPERATOR_TYPE)-operator

include hack/mk/main.mk
