# permissions for end users to edit lmsmoodles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lms-moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: lms-lmsmoodle-editor-role
rules:
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles/status
  verbs:
  - get
