# permissions for end users to view lmsmoodles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lms-moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: lms-lmsmoodle-viewer-role
rules:
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles/status
  verbs:
  - get
