# permissions for end users to edit lmsmoodles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lmsmoodle-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lms-moodle-operator
    app.kubernetes.io/part-of: lms-moodle-operator
    app.kubernetes.io/managed-by: kustomize
  name: lmsmoodle-editor-role
rules:
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles/status
  verbs:
  - get
