---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - keydb.krestomat.io
  resources:
  - keydbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles/finalizers
  verbs:
  - update
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodletemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodletemplates/finalizers
  verbs:
  - update
- apiGroups:
  - lms.krestomat.io
  resources:
  - lmsmoodletemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - m4e.krestomat.io
  resources:
  - moodles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nfs.krestomat.io
  resources:
  - ganeshas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.krestomat.io
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
