apiVersion: m4e.app.krestomat.io/v1alpha1
kind: Flavor
metadata:
  name: flavor-sample
spec:
  ## Moodle new instance
  # moodleNewInstance: true
  moodleNewInstanceFullname: Demo site
  moodleNewInstanceShortname: demo
  moodleNewInstanceSummary: A demo site
  moodleNewInstanceAdminuser: admin
  ## Admin credentials. MUST CHANGED
  moodleNewInstanceAdminpass: secret
  moodleNewInstanceAdminmail: admin@example.com
  moodleNewInstanceAgreeLicense: true
