apiVersion: m4e.krestomat.io/v1alpha1
kind: Flavor
metadata:
  name: flavor-sample
spec:
  m4eSpec:
    ## Moodle new instance
    # moodleNewInstance: true
    moodleNewInstanceAgreeLicense: true
    moodleNewInstanceFullname: Demo site
    moodleNewInstanceShortname: demo
    moodleNewInstanceSummary: A demo site
    ## Admin credentials. MUST CHANGED
    moodleNewInstanceAdminuser: admin
    moodleNewInstanceAdminmail: admin@example.com
    ### 'changeme' as admin password:
    moodleNewAdminpassHash: $2b$10$zbRuwPil1wNWQUkvlkchwe3/rOljJvoheydndKH1X0bdIIigy0xim
    # MoodlePvcMoodledataSize: 1Gi
    # moodlePvcMoodledataStorageAccessMode: ReadWriteOnce
    # moodlePvcMoodledataStorageClassName: standard
  nfsSpec:
    # Ownership/permissions
    ## Set export folder userid to 48
    serverExportUserid: 48
    ## Set export folder groupid to 0
    serverExportGroupid: 0
    ## Set export folder permissions to 775
    serverExportPermissions: "0755"

    # Autoexpansion: if storage available is less than 20% or 'server_pvc_autoexpansion_gib', adjust PVC storage size according to 'server_pvc_autoexpansion_gib' and 'server_pvc_autoexpansion_cap_gib':
    # * Kubernetes cluster and (NFS) Server PVC must support expansion of volumes
    # * In older version, (NFS) Server pod may be restart when autoexpanding if Kubernetes feature gate
    #   'ExpandInUsePersistentVolumes' is false. See:
    #   https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
    ## Enable autoexpansion
    serverPvcAutoexpansion: true
    ## Every time autoexpansion is required, increment 5 GiB
    serverPvcAutoexpansionGib: 5
    ## But no more than 250 GiB
    serverPvcAutoexpansionCapGib: 250
    # Other
    ## (NFS) Server PVC initial size in GiB
    serverPvcInitSizeGib: 1

    ## Storage class name to be used by this (NFS) Server
    # serverPvcStorageClassName: standard
