# Install depandant operators
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lms-moodle-test
namePrefix: lms-moodle-
resources:
- ../crd
- ../rbac
- ../manager
images:
- name: testing
  newName: testing-operator
patches:
- path: manager_image.yaml
- path: ../default/manager_metrics_patch.yaml
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-devel=true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-time-encoding=iso8601
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-encoder=console
  target:
    kind: Deployment
