# Install depandant operators
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kio-test
namePrefix: kio-
resources:
- ../crd
- ../rbac
- ../manager
patchesStrategicMerge:
- ../default/manager_auth_proxy_patch.yaml
- manager_image.yaml
images:
- name: testing
  newName: testing-operator
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-devel=true
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-time-encoding=iso8601
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-encoder=console
  target:
    kind: Deployment
