apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: image
    max_concurrency: 1
    context: "image"
    always_run: false
    require_run: false
    trigger: (?m)^/test( all| group| image),?(s+|$)
    rerun_command: /test image
    source: "image.yaml"
  - name: k8s
    max_concurrency: 1
    context: "k8s"
    always_run: false
    require_run: true
    trigger: (?m)^/test( all| group| k8s),?(s+|$)
    rerun_command: /test k8s
    source: "k8s.yaml"
  - name: test
    context: "test"
    always_run: true
    trigger: (?m)^/test( all| test),?(s+|$)
    rerun_command: /test test
    source: "go-task.yaml"
  - name: lint
    context: "lint"
    always_run: true
    trigger: (?m)^/test( all| lint),?(s+|$)
    rerun_command: /test lint
    source: "go-task.yaml"
  postsubmits:
  - name: release
    max_concurrency: 1
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
